In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [58]:
dataset=pd.read_csv('iris.csv')
X=dataset.iloc[:,:4].values
y=dataset['variety'].values
dataset.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [60]:
pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=c85e88bc7c1b4d65a7ebc42d810dd1becff84702943b747adb37b1fbce4bb706
  Stored in directory: /home/sjcet/.cache/pip/wheels/e4/7b/98/b6466d71b8d738a0c547008b9eb39bf8676d1ff6ca4b22af1c
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split ( X,y, test_size=0.20)

In [68]:
print(X_train)

[[5.5 3.5 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [5.5 2.5 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [6.3 2.7 4.9 1.8]
 [5.2 4.1 1.5 0.1]
 [5.7 2.5 5.  2. ]
 [7.2 3.2 6.  1.8]
 [6.7 3.  5.  1.7]
 [5.6 2.8 4.9 2. ]
 [5.  3.5 1.3 0.3]
 [5.  3.6 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [6.3 2.8 5.1 1.5]
 [6.3 2.9 5.6 1.8]
 [5.5 4.2 1.4 0.2]
 [6.1 2.9 4.7 1.4]
 [5.1 3.8 1.5 0.3]
 [6.9 3.1 5.1 2.3]
 [6.  3.4 4.5 1.6]
 [4.4 3.  1.3 0.2]
 [5.7 3.  4.2 1.2]
 [5.1 3.8 1.6 0.2]
 [5.8 2.7 3.9 1.2]
 [6.7 3.1 5.6 2.4]
 [5.4 3.4 1.7 0.2]
 [4.7 3.2 1.6 0.2]
 [5.  3.4 1.6 0.4]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.7 1.2]
 [5.  3.2 1.2 0.2]
 [6.  2.7 5.1 1.6]
 [4.9 3.6 1.4 0.1]
 [7.2 3.  5.8 1.6]
 [5.8 2.7 5.1 1.9]
 [5.  3.4 1.5 0.2]
 [7.6 3.  6.6 2.1]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [6.5 3.2 5.1 2. ]
 [5.6 2.7 4.2 1.3]
 [6.3 2.5 4.9 1.5]
 [6.6 2.9 4.6 1.3]
 [7.9 3.8 6.4 2. ]
 [5.5 2.4 3.7 1. ]
 [4.3 3.  1.1 0.1]
 [5.4 3.4 1.5 0.4]
 [5.  3.  1.6 0.2]
 [5.5 2.4 3.8 1.1]
 [4.9 3.1 1.5 0.2]
 [6.7 3.1 4.7 1.5]
 [6.4 3.1 5.5 1.8]
 [5.5 2.3 4.

In [69]:
print(y_train)

['Setosa' 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Setosa'
 'Virginica' 'Virginica' 'Versicolor' 'Virginica' 'Setosa' 'Setosa'
 'Setosa' 'Virginica' 'Virginica' 'Setosa' 'Versicolor' 'Setosa'
 'Virginica' 'Versicolor' 'Setosa' 'Versicolor' 'Setosa' 'Versicolor'
 'Virginica' 'Setosa' 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Setosa'
 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Setosa' 'Virginica'
 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Versicolor' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Setosa'
 'Versicolor' 'Setosa' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Setosa' 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Virginica'
 'Setosa' 'Virginica' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Setosa' 'Versicolor' 'Setosa' 'Setosa' 'Versicolor' 'Versicolor'
 'Virginica' 'Virginica' 'Setosa' 'Versicolor' 'Virginica' 'Virginica'
 'Virginica' 'Virginica' 'Versicolor' 'Virginica' 'Virginica' 'Virginica'
 'Versicolor' 'Versicolor'

In [98]:
from sklearn.naive_bayes import Gaussian
classifier=Gaussian()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import accuracy_score
print("accuracy",accuracy_score(y_test,y_pred))

ImportError: cannot import name 'Gaussian' from 'sklearn.naive_bayes' (/home/sjcet/anaconda3/lib/python3.9/site-packages/sklearn/naive_bayes.py)